// GENERATED - Jake UI icon map (Figma "Icon" set -> @phosphor-icons/react)
//
// Source: Figma component set 158:4066, rebuilt 8 Aug 2026 from the real
// Phosphor regular SVG paths in @phosphor-icons/core. Figma variant names are
// Phosphor component names verbatim, with one exception: SidebarSimpleRight,
// which Phosphor has no icon for and which renders as <SidebarSimple mirrored />.
//
// To regenerate: re-read the Name axis of set 158:4066 and re-emit this table.
// figmaNodeId points at the 16px variant of each icon.

import type { ComponentType } from "react";
import type { IconProps } from "@phosphor-icons/react";
import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowSquareOut,
  ArrowUp,
  ArrowsClockwise,
  Bell,
  CalendarBlank,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  Check,
  CheckCircle,
  Clock,
  Copy,
  DotsThree,
  DotsThreeVertical,
  DownloadSimple,
  Envelope,
  Eye,
  EyeSlash,
  File,
  Folder,
  Funnel,
  Gear,
  House,
  Info,
  Link,
  List,
  Lock,
  LockOpen,
  MagnifyingGlass,
  Minus,
  MinusCircle,
  Pause,
  PencilSimple,
  Play,
  Plus,
  PlusCircle,
  Question,
  SidebarSimple,
  SortAscending,
  SortDescending,
  Trash,
  UploadSimple,
  User,
  Users,
  Warning,
  WarningCircle,
  X,
} from "@phosphor-icons/react";

export type IconSize = 16 | 20 | 24;

export interface IconEntry {
  /** Component from @phosphor-icons/react */
  Icon: ComponentType<IconProps>;
  /** Phosphor renders this flipped horizontally */
  mirrored: boolean;
  /** Figma variant name (Name axis) */
  figmaName: string;
  /** Figma node id of the 16px variant */
  figmaNodeId: string;
}

/** Figma "Name" variant value -> Phosphor component. 52 icons, sizes 16/20/24. */
export const ICONS = {
  Plus: { Icon: Plus, mirrored: false, figmaName: "Plus", figmaNodeId: "158:3502" },
  Minus: { Icon: Minus, mirrored: false, figmaName: "Minus", figmaNodeId: "158:3511" },
  Check: { Icon: Check, mirrored: false, figmaName: "Check", figmaNodeId: "158:3520" },
  X: { Icon: X, mirrored: false, figmaName: "X", figmaNodeId: "158:3529" },
  CaretDown: { Icon: CaretDown, mirrored: false, figmaName: "CaretDown", figmaNodeId: "158:3538" },
  CaretUp: { Icon: CaretUp, mirrored: false, figmaName: "CaretUp", figmaNodeId: "158:3547" },
  CaretLeft: { Icon: CaretLeft, mirrored: false, figmaName: "CaretLeft", figmaNodeId: "158:3556" },
  CaretRight: { Icon: CaretRight, mirrored: false, figmaName: "CaretRight", figmaNodeId: "158:3565" },
  ArrowLeft: { Icon: ArrowLeft, mirrored: false, figmaName: "ArrowLeft", figmaNodeId: "158:3574" },
  ArrowRight: { Icon: ArrowRight, mirrored: false, figmaName: "ArrowRight", figmaNodeId: "158:3583" },
  ArrowUp: { Icon: ArrowUp, mirrored: false, figmaName: "ArrowUp", figmaNodeId: "158:3592" },
  ArrowDown: { Icon: ArrowDown, mirrored: false, figmaName: "ArrowDown", figmaNodeId: "158:3601" },
  CalendarBlank: { Icon: CalendarBlank, mirrored: false, figmaName: "CalendarBlank", figmaNodeId: "158:3610" },
  MagnifyingGlass: { Icon: MagnifyingGlass, mirrored: false, figmaName: "MagnifyingGlass", figmaNodeId: "158:3622" },
  Funnel: { Icon: Funnel, mirrored: false, figmaName: "Funnel", figmaNodeId: "158:3634" },
  DownloadSimple: { Icon: DownloadSimple, mirrored: false, figmaName: "DownloadSimple", figmaNodeId: "158:3643" },
  UploadSimple: { Icon: UploadSimple, mirrored: false, figmaName: "UploadSimple", figmaNodeId: "158:3652" },
  DotsThree: { Icon: DotsThree, mirrored: false, figmaName: "DotsThree", figmaNodeId: "158:3661" },
  DotsThreeVertical: { Icon: DotsThreeVertical, mirrored: false, figmaName: "DotsThreeVertical", figmaNodeId: "158:3676" },
  Info: { Icon: Info, mirrored: false, figmaName: "Info", figmaNodeId: "158:3691" },
  CheckCircle: { Icon: CheckCircle, mirrored: false, figmaName: "CheckCircle", figmaNodeId: "158:3703" },
  WarningCircle: { Icon: WarningCircle, mirrored: false, figmaName: "WarningCircle", figmaNodeId: "158:3715" },
  Warning: { Icon: Warning, mirrored: false, figmaName: "Warning", figmaNodeId: "158:3727" },
  List: { Icon: List, mirrored: false, figmaName: "List", figmaNodeId: "158:3739" },
  User: { Icon: User, mirrored: false, figmaName: "User", figmaNodeId: "158:3748" },
  Users: { Icon: Users, mirrored: false, figmaName: "Users", figmaNodeId: "158:3760" },
  Gear: { Icon: Gear, mirrored: false, figmaName: "Gear", figmaNodeId: "158:3775" },
  Bell: { Icon: Bell, mirrored: false, figmaName: "Bell", figmaNodeId: "158:3787" },
  Envelope: { Icon: Envelope, mirrored: false, figmaName: "Envelope", figmaNodeId: "158:3796" },
  Link: { Icon: Link, mirrored: false, figmaName: "Link", figmaNodeId: "158:3808" },
  Copy: { Icon: Copy, mirrored: false, figmaName: "Copy", figmaNodeId: "158:3817" },
  Trash: { Icon: Trash, mirrored: false, figmaName: "Trash", figmaNodeId: "158:3829" },
  PencilSimple: { Icon: PencilSimple, mirrored: false, figmaName: "PencilSimple", figmaNodeId: "158:3838" },
  ArrowSquareOut: { Icon: ArrowSquareOut, mirrored: false, figmaName: "ArrowSquareOut", figmaNodeId: "158:3850" },
  Eye: { Icon: Eye, mirrored: false, figmaName: "Eye", figmaNodeId: "158:3862" },
  EyeSlash: { Icon: EyeSlash, mirrored: false, figmaName: "EyeSlash", figmaNodeId: "158:3874" },
  Lock: { Icon: Lock, mirrored: false, figmaName: "Lock", figmaNodeId: "158:3883" },
  LockOpen: { Icon: LockOpen, mirrored: false, figmaName: "LockOpen", figmaNodeId: "158:3895" },
  Folder: { Icon: Folder, mirrored: false, figmaName: "Folder", figmaNodeId: "158:3907" },
  File: { Icon: File, mirrored: false, figmaName: "File", figmaNodeId: "158:3916" },
  House: { Icon: House, mirrored: false, figmaName: "House", figmaNodeId: "158:3928" },
  ArrowsClockwise: { Icon: ArrowsClockwise, mirrored: false, figmaName: "ArrowsClockwise", figmaNodeId: "158:3940" },
  SortAscending: { Icon: SortAscending, mirrored: false, figmaName: "SortAscending", figmaNodeId: "158:3952" },
  SortDescending: { Icon: SortDescending, mirrored: false, figmaName: "SortDescending", figmaNodeId: "158:3961" },
  SidebarSimple: { Icon: SidebarSimple, mirrored: false, figmaName: "SidebarSimple", figmaNodeId: "158:3970" },
  SidebarSimpleRight: { Icon: SidebarSimple, mirrored: true, figmaName: "SidebarSimpleRight", figmaNodeId: "158:3982" },
  PlusCircle: { Icon: PlusCircle, mirrored: false, figmaName: "PlusCircle", figmaNodeId: "158:3994" },
  MinusCircle: { Icon: MinusCircle, mirrored: false, figmaName: "MinusCircle", figmaNodeId: "158:4006" },
  Clock: { Icon: Clock, mirrored: false, figmaName: "Clock", figmaNodeId: "158:4018" },
  Question: { Icon: Question, mirrored: false, figmaName: "Question", figmaNodeId: "158:4030" },
  Play: { Icon: Play, mirrored: false, figmaName: "Play", figmaNodeId: "158:4042" },
  Pause: { Icon: Pause, mirrored: false, figmaName: "Pause", figmaNodeId: "158:4054" },
} as const satisfies Record<string, IconEntry>;

export type IconName = keyof typeof ICONS;

/** Names used before the Phosphor migration (2026-08-08). For codemods only. */
export const LEGACY_ALIASES: Record<string, IconName> = {
  "Add": "Plus",
  "Minus": "Minus",
  "Check": "Check",
  "Close": "X",
  "Chevron Down": "CaretDown",
  "Chevron Up": "CaretUp",
  "Chevron Left": "CaretLeft",
  "Chevron Right": "CaretRight",
  "Arrow Left": "ArrowLeft",
  "Arrow Right": "ArrowRight",
  "Arrow Up": "ArrowUp",
  "Arrow Down": "ArrowDown",
  "Calendar": "CalendarBlank",
  "Search": "MagnifyingGlass",
  "Filter": "Funnel",
  "Download": "DownloadSimple",
  "Upload": "UploadSimple",
  "More Horizontal": "DotsThree",
  "More Vertical": "DotsThreeVertical",
  "Info": "Info",
  "Circle Check": "CheckCircle",
  "Circle Alert": "WarningCircle",
  "Triangle Alert": "Warning",
  "Menu": "List",
  "User": "User",
  "Users": "Users",
  "Settings": "Gear",
  "Bell": "Bell",
  "Mail": "Envelope",
  "Link": "Link",
  "Copy": "Copy",
  "Trash": "Trash",
  "Edit": "PencilSimple",
  "External Link": "ArrowSquareOut",
  "Eye": "Eye",
  "Eye Off": "EyeSlash",
  "Lock": "Lock",
  "Unlock": "LockOpen",
  "Folder": "Folder",
  "File": "File",
  "Home": "House",
  "Refresh": "ArrowsClockwise",
  "Sort Ascending": "SortAscending",
  "Sort Descending": "SortDescending",
  "Panel Left": "SidebarSimple",
  "Panel Right": "SidebarSimpleRight",
  "Circle Plus": "PlusCircle",
  "Circle Minus": "MinusCircle",
  "Clock": "Clock",
  "Help": "Question",
  "Play": "Play",
  "Pause": "Pause",
};
